// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3.op
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module gZip_cu_huffman_encode (
        ap_start,
        start_full_n,
        start_out,
        start_write,
        inStream_V_V_dout,
        inStream_V_V_empty_n,
        inStream_V_V_read,
        outStream_V_V_din,
        outStream_V_V_full_n,
        outStream_V_V_write,
        input_size_dout,
        input_size_empty_n,
        input_size_read,
        ap_clk,
        ap_rst,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue,
        ap_ext_blocking_n,
        ap_str_blocking_n,
        ap_int_blocking_n
);


input   ap_start;
input   start_full_n;
output   start_out;
output   start_write;
input  [255:0] inStream_V_V_dout;
input   inStream_V_V_empty_n;
output   inStream_V_V_read;
output  [63:0] outStream_V_V_din;
input   outStream_V_V_full_n;
output   outStream_V_V_write;
input  [63:0] input_size_dout;
input   input_size_empty_n;
output   input_size_read;
input   ap_clk;
input   ap_rst;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;
output   ap_ext_blocking_n;
output   ap_str_blocking_n;
output   ap_int_blocking_n;

reg start_write;

reg    real_start;
reg    start_once_reg;
wire    internal_ap_ready;
wire    splitter_U0_ap_start;
wire    splitter_U0_start_full_n;
wire    splitter_U0_ap_done;
wire    splitter_U0_ap_continue;
wire    splitter_U0_ap_idle;
wire    splitter_U0_ap_ready;
wire    splitter_U0_start_out;
wire    splitter_U0_start_write;
wire    splitter_U0_inStream_V_V_read;
wire   [255:0] splitter_U0_outStream0_V_V_din;
wire    splitter_U0_outStream0_V_V_write;
wire   [255:0] splitter_U0_outStream1_V_V_din;
wire    splitter_U0_outStream1_V_V_write;
wire   [255:0] splitter_U0_outStream2_V_V_din;
wire    splitter_U0_outStream2_V_V_write;
wire   [255:0] splitter_U0_outStream3_V_V_din;
wire    splitter_U0_outStream3_V_V_write;
wire   [255:0] splitter_U0_outStream4_V_V_din;
wire    splitter_U0_outStream4_V_V_write;
wire   [255:0] splitter_U0_outStream5_V_V_din;
wire    splitter_U0_outStream5_V_V_write;
wire   [255:0] splitter_U0_outStream6_V_V_din;
wire    splitter_U0_outStream6_V_V_write;
wire   [255:0] splitter_U0_outStream7_V_V_din;
wire    splitter_U0_outStream7_V_V_write;
wire    splitter_U0_input_size_read;
wire   [63:0] splitter_U0_input_size_out_din;
wire    splitter_U0_input_size_out_write;
wire    splitter_U0_ap_ext_blocking_n;
wire    splitter_U0_ap_str_blocking_n;
wire    splitter_U0_ap_int_blocking_n;
wire    fixedHuffman83_U0_ap_start;
wire    fixedHuffman83_U0_ap_done;
wire    fixedHuffman83_U0_ap_continue;
wire    fixedHuffman83_U0_ap_idle;
wire    fixedHuffman83_U0_ap_ready;
wire    fixedHuffman83_U0_inStream_V_V_read;
wire   [63:0] fixedHuffman83_U0_outStream_V_V_din;
wire    fixedHuffman83_U0_outStream_V_V_write;
wire   [15:0] fixedHuffman83_U0_outStreamSizeInBits_V_din;
wire    fixedHuffman83_U0_outStreamSizeInBits_V_write;
wire    fixedHuffman83_U0_ap_ext_blocking_n;
wire    fixedHuffman83_U0_ap_str_blocking_n;
wire    fixedHuffman83_U0_ap_int_blocking_n;
wire    fixedHuffman84_U0_ap_start;
wire    fixedHuffman84_U0_ap_done;
wire    fixedHuffman84_U0_ap_continue;
wire    fixedHuffman84_U0_ap_idle;
wire    fixedHuffman84_U0_ap_ready;
wire    fixedHuffman84_U0_inStream_V_V_read;
wire   [63:0] fixedHuffman84_U0_outStream_V_V_din;
wire    fixedHuffman84_U0_outStream_V_V_write;
wire   [15:0] fixedHuffman84_U0_outStreamSizeInBits_V_din;
wire    fixedHuffman84_U0_outStreamSizeInBits_V_write;
wire    fixedHuffman84_U0_ap_ext_blocking_n;
wire    fixedHuffman84_U0_ap_str_blocking_n;
wire    fixedHuffman84_U0_ap_int_blocking_n;
wire    fixedHuffman85_U0_ap_start;
wire    fixedHuffman85_U0_ap_done;
wire    fixedHuffman85_U0_ap_continue;
wire    fixedHuffman85_U0_ap_idle;
wire    fixedHuffman85_U0_ap_ready;
wire    fixedHuffman85_U0_inStream_V_V_read;
wire   [63:0] fixedHuffman85_U0_outStream_V_V_din;
wire    fixedHuffman85_U0_outStream_V_V_write;
wire   [15:0] fixedHuffman85_U0_outStreamSizeInBits_V_din;
wire    fixedHuffman85_U0_outStreamSizeInBits_V_write;
wire    fixedHuffman85_U0_ap_ext_blocking_n;
wire    fixedHuffman85_U0_ap_str_blocking_n;
wire    fixedHuffman85_U0_ap_int_blocking_n;
wire    fixedHuffman86_U0_ap_start;
wire    fixedHuffman86_U0_ap_done;
wire    fixedHuffman86_U0_ap_continue;
wire    fixedHuffman86_U0_ap_idle;
wire    fixedHuffman86_U0_ap_ready;
wire    fixedHuffman86_U0_inStream_V_V_read;
wire   [63:0] fixedHuffman86_U0_outStream_V_V_din;
wire    fixedHuffman86_U0_outStream_V_V_write;
wire   [15:0] fixedHuffman86_U0_outStreamSizeInBits_V_din;
wire    fixedHuffman86_U0_outStreamSizeInBits_V_write;
wire    fixedHuffman86_U0_ap_ext_blocking_n;
wire    fixedHuffman86_U0_ap_str_blocking_n;
wire    fixedHuffman86_U0_ap_int_blocking_n;
wire    fixedHuffman87_U0_ap_start;
wire    fixedHuffman87_U0_ap_done;
wire    fixedHuffman87_U0_ap_continue;
wire    fixedHuffman87_U0_ap_idle;
wire    fixedHuffman87_U0_ap_ready;
wire    fixedHuffman87_U0_inStream_V_V_read;
wire   [63:0] fixedHuffman87_U0_outStream_V_V_din;
wire    fixedHuffman87_U0_outStream_V_V_write;
wire   [15:0] fixedHuffman87_U0_outStreamSizeInBits_V_din;
wire    fixedHuffman87_U0_outStreamSizeInBits_V_write;
wire    fixedHuffman87_U0_ap_ext_blocking_n;
wire    fixedHuffman87_U0_ap_str_blocking_n;
wire    fixedHuffman87_U0_ap_int_blocking_n;
wire    fixedHuffman88_U0_ap_start;
wire    fixedHuffman88_U0_ap_done;
wire    fixedHuffman88_U0_ap_continue;
wire    fixedHuffman88_U0_ap_idle;
wire    fixedHuffman88_U0_ap_ready;
wire    fixedHuffman88_U0_inStream_V_V_read;
wire   [63:0] fixedHuffman88_U0_outStream_V_V_din;
wire    fixedHuffman88_U0_outStream_V_V_write;
wire   [15:0] fixedHuffman88_U0_outStreamSizeInBits_V_din;
wire    fixedHuffman88_U0_outStreamSizeInBits_V_write;
wire    fixedHuffman88_U0_ap_ext_blocking_n;
wire    fixedHuffman88_U0_ap_str_blocking_n;
wire    fixedHuffman88_U0_ap_int_blocking_n;
wire    fixedHuffman89_U0_ap_start;
wire    fixedHuffman89_U0_ap_done;
wire    fixedHuffman89_U0_ap_continue;
wire    fixedHuffman89_U0_ap_idle;
wire    fixedHuffman89_U0_ap_ready;
wire    fixedHuffman89_U0_inStream_V_V_read;
wire   [63:0] fixedHuffman89_U0_outStream_V_V_din;
wire    fixedHuffman89_U0_outStream_V_V_write;
wire   [15:0] fixedHuffman89_U0_outStreamSizeInBits_V_din;
wire    fixedHuffman89_U0_outStreamSizeInBits_V_write;
wire    fixedHuffman89_U0_ap_ext_blocking_n;
wire    fixedHuffman89_U0_ap_str_blocking_n;
wire    fixedHuffman89_U0_ap_int_blocking_n;
wire    fixedHuffman_U0_ap_start;
wire    fixedHuffman_U0_ap_done;
wire    fixedHuffman_U0_ap_continue;
wire    fixedHuffman_U0_ap_idle;
wire    fixedHuffman_U0_ap_ready;
wire    fixedHuffman_U0_inStream_V_V_read;
wire   [63:0] fixedHuffman_U0_outStream_V_V_din;
wire    fixedHuffman_U0_outStream_V_V_write;
wire   [15:0] fixedHuffman_U0_outStreamSizeInBits_V_din;
wire    fixedHuffman_U0_outStreamSizeInBits_V_write;
wire    fixedHuffman_U0_ap_ext_blocking_n;
wire    fixedHuffman_U0_ap_str_blocking_n;
wire    fixedHuffman_U0_ap_int_blocking_n;
wire    merger_U0_ap_start;
wire    merger_U0_ap_done;
wire    merger_U0_ap_continue;
wire    merger_U0_ap_idle;
wire    merger_U0_ap_ready;
wire   [63:0] merger_U0_outStream_V_V_din;
wire    merger_U0_outStream_V_V_write;
wire    merger_U0_inStream0_V_V_read;
wire    merger_U0_inStreamSizeInBits0_V_read;
wire    merger_U0_inStream1_V_V_read;
wire    merger_U0_inStreamSizeInBits1_V_read;
wire    merger_U0_inStream2_V_V_read;
wire    merger_U0_inStreamSizeInBits2_V_read;
wire    merger_U0_inStream3_V_V_read;
wire    merger_U0_inStreamSizeInBits3_V_read;
wire    merger_U0_inStream4_V_V_read;
wire    merger_U0_inStreamSizeInBits4_V_read;
wire    merger_U0_inStream5_V_V_read;
wire    merger_U0_inStreamSizeInBits5_V_read;
wire    merger_U0_inStream6_V_V_read;
wire    merger_U0_inStreamSizeInBits6_V_read;
wire    merger_U0_inStream7_V_V_read;
wire    merger_U0_inStreamSizeInBits7_V_read;
wire    merger_U0_input_size_read;
wire    merger_U0_ap_ext_blocking_n;
wire    merger_U0_ap_str_blocking_n;
wire    merger_U0_ap_int_blocking_n;
wire    ap_sync_continue;
wire    inStream0_V_V_full_n;
wire   [255:0] inStream0_V_V_dout;
wire    inStream0_V_V_empty_n;
wire    inStream1_V_V_full_n;
wire   [255:0] inStream1_V_V_dout;
wire    inStream1_V_V_empty_n;
wire    inStream2_V_V_full_n;
wire   [255:0] inStream2_V_V_dout;
wire    inStream2_V_V_empty_n;
wire    inStream3_V_V_full_n;
wire   [255:0] inStream3_V_V_dout;
wire    inStream3_V_V_empty_n;
wire    inStream4_V_V_full_n;
wire   [255:0] inStream4_V_V_dout;
wire    inStream4_V_V_empty_n;
wire    inStream5_V_V_full_n;
wire   [255:0] inStream5_V_V_dout;
wire    inStream5_V_V_empty_n;
wire    inStream6_V_V_full_n;
wire   [255:0] inStream6_V_V_dout;
wire    inStream6_V_V_empty_n;
wire    inStream7_V_V_full_n;
wire   [255:0] inStream7_V_V_dout;
wire    inStream7_V_V_empty_n;
wire    input_size_c_i_full_n;
wire   [63:0] input_size_c_i_dout;
wire    input_size_c_i_empty_n;
wire    outStream0_V_V_full_n;
wire   [63:0] outStream0_V_V_dout;
wire    outStream0_V_V_empty_n;
wire    outStreamSizeInBits0_V_full_n;
wire   [15:0] outStreamSizeInBits0_V_dout;
wire    outStreamSizeInBits0_V_empty_n;
wire    outStream1_V_V_full_n;
wire   [63:0] outStream1_V_V_dout;
wire    outStream1_V_V_empty_n;
wire    outStreamSizeInBits1_V_full_n;
wire   [15:0] outStreamSizeInBits1_V_dout;
wire    outStreamSizeInBits1_V_empty_n;
wire    outStream2_V_V_full_n;
wire   [63:0] outStream2_V_V_dout;
wire    outStream2_V_V_empty_n;
wire    outStreamSizeInBits2_V_full_n;
wire   [15:0] outStreamSizeInBits2_V_dout;
wire    outStreamSizeInBits2_V_empty_n;
wire    outStream3_V_V_full_n;
wire   [63:0] outStream3_V_V_dout;
wire    outStream3_V_V_empty_n;
wire    outStreamSizeInBits3_V_full_n;
wire   [15:0] outStreamSizeInBits3_V_dout;
wire    outStreamSizeInBits3_V_empty_n;
wire    outStream4_V_V_full_n;
wire   [63:0] outStream4_V_V_dout;
wire    outStream4_V_V_empty_n;
wire    outStreamSizeInBits4_V_full_n;
wire   [15:0] outStreamSizeInBits4_V_dout;
wire    outStreamSizeInBits4_V_empty_n;
wire    outStream5_V_V_full_n;
wire   [63:0] outStream5_V_V_dout;
wire    outStream5_V_V_empty_n;
wire    outStreamSizeInBits5_V_full_n;
wire   [15:0] outStreamSizeInBits5_V_dout;
wire    outStreamSizeInBits5_V_empty_n;
wire    outStream6_V_V_full_n;
wire   [63:0] outStream6_V_V_dout;
wire    outStream6_V_V_empty_n;
wire    outStreamSizeInBits6_V_full_n;
wire   [15:0] outStreamSizeInBits6_V_dout;
wire    outStreamSizeInBits6_V_empty_n;
wire    outStream7_V_V_full_n;
wire   [63:0] outStream7_V_V_dout;
wire    outStream7_V_V_empty_n;
wire    outStreamSizeInBits7_V_full_n;
wire   [15:0] outStreamSizeInBits7_V_dout;
wire    outStreamSizeInBits7_V_empty_n;
wire    ap_sync_done;
wire    ap_sync_ready;
wire   [0:0] start_for_fixedHuffman83_U0_din;
wire    start_for_fixedHuffman83_U0_full_n;
wire   [0:0] start_for_fixedHuffman83_U0_dout;
wire    start_for_fixedHuffman83_U0_empty_n;
wire   [0:0] start_for_fixedHuffman84_U0_din;
wire    start_for_fixedHuffman84_U0_full_n;
wire   [0:0] start_for_fixedHuffman84_U0_dout;
wire    start_for_fixedHuffman84_U0_empty_n;
wire   [0:0] start_for_fixedHuffman85_U0_din;
wire    start_for_fixedHuffman85_U0_full_n;
wire   [0:0] start_for_fixedHuffman85_U0_dout;
wire    start_for_fixedHuffman85_U0_empty_n;
wire   [0:0] start_for_fixedHuffman86_U0_din;
wire    start_for_fixedHuffman86_U0_full_n;
wire   [0:0] start_for_fixedHuffman86_U0_dout;
wire    start_for_fixedHuffman86_U0_empty_n;
wire   [0:0] start_for_fixedHuffman87_U0_din;
wire    start_for_fixedHuffman87_U0_full_n;
wire   [0:0] start_for_fixedHuffman87_U0_dout;
wire    start_for_fixedHuffman87_U0_empty_n;
wire   [0:0] start_for_fixedHuffman88_U0_din;
wire    start_for_fixedHuffman88_U0_full_n;
wire   [0:0] start_for_fixedHuffman88_U0_dout;
wire    start_for_fixedHuffman88_U0_empty_n;
wire   [0:0] start_for_fixedHuffman89_U0_din;
wire    start_for_fixedHuffman89_U0_full_n;
wire   [0:0] start_for_fixedHuffman89_U0_dout;
wire    start_for_fixedHuffman89_U0_empty_n;
wire   [0:0] start_for_fixedHuffman_U0_din;
wire    start_for_fixedHuffman_U0_full_n;
wire   [0:0] start_for_fixedHuffman_U0_dout;
wire    start_for_fixedHuffman_U0_empty_n;
wire   [0:0] start_for_merger_U0_din;
wire    start_for_merger_U0_full_n;
wire   [0:0] start_for_merger_U0_dout;
wire    start_for_merger_U0_empty_n;
wire    fixedHuffman83_U0_start_full_n;
wire    fixedHuffman83_U0_start_write;
wire    fixedHuffman84_U0_start_full_n;
wire    fixedHuffman84_U0_start_write;
wire    fixedHuffman85_U0_start_full_n;
wire    fixedHuffman85_U0_start_write;
wire    fixedHuffman86_U0_start_full_n;
wire    fixedHuffman86_U0_start_write;
wire    fixedHuffman87_U0_start_full_n;
wire    fixedHuffman87_U0_start_write;
wire    fixedHuffman88_U0_start_full_n;
wire    fixedHuffman88_U0_start_write;
wire    fixedHuffman89_U0_start_full_n;
wire    fixedHuffman89_U0_start_write;
wire    fixedHuffman_U0_start_full_n;
wire    fixedHuffman_U0_start_write;
wire    merger_U0_start_full_n;
wire    merger_U0_start_write;
wire    ap_ext_blocking_cur_n;
wire    ap_str_blocking_cur_n;
wire    ap_int_blocking_cur_n;
wire    ap_ext_blocking_sub_n;
wire    ap_str_blocking_sub_n;
wire    ap_int_blocking_sub_n;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
end

gZip_cu_splitter splitter_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(splitter_U0_ap_start),
    .start_full_n(splitter_U0_start_full_n),
    .ap_done(splitter_U0_ap_done),
    .ap_continue(splitter_U0_ap_continue),
    .ap_idle(splitter_U0_ap_idle),
    .ap_ready(splitter_U0_ap_ready),
    .start_out(splitter_U0_start_out),
    .start_write(splitter_U0_start_write),
    .inStream_V_V_dout(inStream_V_V_dout),
    .inStream_V_V_empty_n(inStream_V_V_empty_n),
    .inStream_V_V_read(splitter_U0_inStream_V_V_read),
    .outStream0_V_V_din(splitter_U0_outStream0_V_V_din),
    .outStream0_V_V_full_n(inStream0_V_V_full_n),
    .outStream0_V_V_write(splitter_U0_outStream0_V_V_write),
    .outStream1_V_V_din(splitter_U0_outStream1_V_V_din),
    .outStream1_V_V_full_n(inStream1_V_V_full_n),
    .outStream1_V_V_write(splitter_U0_outStream1_V_V_write),
    .outStream2_V_V_din(splitter_U0_outStream2_V_V_din),
    .outStream2_V_V_full_n(inStream2_V_V_full_n),
    .outStream2_V_V_write(splitter_U0_outStream2_V_V_write),
    .outStream3_V_V_din(splitter_U0_outStream3_V_V_din),
    .outStream3_V_V_full_n(inStream3_V_V_full_n),
    .outStream3_V_V_write(splitter_U0_outStream3_V_V_write),
    .outStream4_V_V_din(splitter_U0_outStream4_V_V_din),
    .outStream4_V_V_full_n(inStream4_V_V_full_n),
    .outStream4_V_V_write(splitter_U0_outStream4_V_V_write),
    .outStream5_V_V_din(splitter_U0_outStream5_V_V_din),
    .outStream5_V_V_full_n(inStream5_V_V_full_n),
    .outStream5_V_V_write(splitter_U0_outStream5_V_V_write),
    .outStream6_V_V_din(splitter_U0_outStream6_V_V_din),
    .outStream6_V_V_full_n(inStream6_V_V_full_n),
    .outStream6_V_V_write(splitter_U0_outStream6_V_V_write),
    .outStream7_V_V_din(splitter_U0_outStream7_V_V_din),
    .outStream7_V_V_full_n(inStream7_V_V_full_n),
    .outStream7_V_V_write(splitter_U0_outStream7_V_V_write),
    .input_size_dout(input_size_dout),
    .input_size_empty_n(input_size_empty_n),
    .input_size_read(splitter_U0_input_size_read),
    .input_size_out_din(splitter_U0_input_size_out_din),
    .input_size_out_full_n(input_size_c_i_full_n),
    .input_size_out_write(splitter_U0_input_size_out_write),
    .ap_ext_blocking_n(splitter_U0_ap_ext_blocking_n),
    .ap_str_blocking_n(splitter_U0_ap_str_blocking_n),
    .ap_int_blocking_n(splitter_U0_ap_int_blocking_n)
);

gZip_cu_fixedHuffman83 fixedHuffman83_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(fixedHuffman83_U0_ap_start),
    .ap_done(fixedHuffman83_U0_ap_done),
    .ap_continue(fixedHuffman83_U0_ap_continue),
    .ap_idle(fixedHuffman83_U0_ap_idle),
    .ap_ready(fixedHuffman83_U0_ap_ready),
    .inStream_V_V_dout(inStream0_V_V_dout),
    .inStream_V_V_empty_n(inStream0_V_V_empty_n),
    .inStream_V_V_read(fixedHuffman83_U0_inStream_V_V_read),
    .outStream_V_V_din(fixedHuffman83_U0_outStream_V_V_din),
    .outStream_V_V_full_n(outStream0_V_V_full_n),
    .outStream_V_V_write(fixedHuffman83_U0_outStream_V_V_write),
    .outStreamSizeInBits_V_din(fixedHuffman83_U0_outStreamSizeInBits_V_din),
    .outStreamSizeInBits_V_full_n(outStreamSizeInBits0_V_full_n),
    .outStreamSizeInBits_V_write(fixedHuffman83_U0_outStreamSizeInBits_V_write),
    .ap_ext_blocking_n(fixedHuffman83_U0_ap_ext_blocking_n),
    .ap_str_blocking_n(fixedHuffman83_U0_ap_str_blocking_n),
    .ap_int_blocking_n(fixedHuffman83_U0_ap_int_blocking_n)
);

gZip_cu_fixedHuffman84 fixedHuffman84_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(fixedHuffman84_U0_ap_start),
    .ap_done(fixedHuffman84_U0_ap_done),
    .ap_continue(fixedHuffman84_U0_ap_continue),
    .ap_idle(fixedHuffman84_U0_ap_idle),
    .ap_ready(fixedHuffman84_U0_ap_ready),
    .inStream_V_V_dout(inStream1_V_V_dout),
    .inStream_V_V_empty_n(inStream1_V_V_empty_n),
    .inStream_V_V_read(fixedHuffman84_U0_inStream_V_V_read),
    .outStream_V_V_din(fixedHuffman84_U0_outStream_V_V_din),
    .outStream_V_V_full_n(outStream1_V_V_full_n),
    .outStream_V_V_write(fixedHuffman84_U0_outStream_V_V_write),
    .outStreamSizeInBits_V_din(fixedHuffman84_U0_outStreamSizeInBits_V_din),
    .outStreamSizeInBits_V_full_n(outStreamSizeInBits1_V_full_n),
    .outStreamSizeInBits_V_write(fixedHuffman84_U0_outStreamSizeInBits_V_write),
    .ap_ext_blocking_n(fixedHuffman84_U0_ap_ext_blocking_n),
    .ap_str_blocking_n(fixedHuffman84_U0_ap_str_blocking_n),
    .ap_int_blocking_n(fixedHuffman84_U0_ap_int_blocking_n)
);

gZip_cu_fixedHuffman85 fixedHuffman85_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(fixedHuffman85_U0_ap_start),
    .ap_done(fixedHuffman85_U0_ap_done),
    .ap_continue(fixedHuffman85_U0_ap_continue),
    .ap_idle(fixedHuffman85_U0_ap_idle),
    .ap_ready(fixedHuffman85_U0_ap_ready),
    .inStream_V_V_dout(inStream2_V_V_dout),
    .inStream_V_V_empty_n(inStream2_V_V_empty_n),
    .inStream_V_V_read(fixedHuffman85_U0_inStream_V_V_read),
    .outStream_V_V_din(fixedHuffman85_U0_outStream_V_V_din),
    .outStream_V_V_full_n(outStream2_V_V_full_n),
    .outStream_V_V_write(fixedHuffman85_U0_outStream_V_V_write),
    .outStreamSizeInBits_V_din(fixedHuffman85_U0_outStreamSizeInBits_V_din),
    .outStreamSizeInBits_V_full_n(outStreamSizeInBits2_V_full_n),
    .outStreamSizeInBits_V_write(fixedHuffman85_U0_outStreamSizeInBits_V_write),
    .ap_ext_blocking_n(fixedHuffman85_U0_ap_ext_blocking_n),
    .ap_str_blocking_n(fixedHuffman85_U0_ap_str_blocking_n),
    .ap_int_blocking_n(fixedHuffman85_U0_ap_int_blocking_n)
);

gZip_cu_fixedHuffman86 fixedHuffman86_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(fixedHuffman86_U0_ap_start),
    .ap_done(fixedHuffman86_U0_ap_done),
    .ap_continue(fixedHuffman86_U0_ap_continue),
    .ap_idle(fixedHuffman86_U0_ap_idle),
    .ap_ready(fixedHuffman86_U0_ap_ready),
    .inStream_V_V_dout(inStream3_V_V_dout),
    .inStream_V_V_empty_n(inStream3_V_V_empty_n),
    .inStream_V_V_read(fixedHuffman86_U0_inStream_V_V_read),
    .outStream_V_V_din(fixedHuffman86_U0_outStream_V_V_din),
    .outStream_V_V_full_n(outStream3_V_V_full_n),
    .outStream_V_V_write(fixedHuffman86_U0_outStream_V_V_write),
    .outStreamSizeInBits_V_din(fixedHuffman86_U0_outStreamSizeInBits_V_din),
    .outStreamSizeInBits_V_full_n(outStreamSizeInBits3_V_full_n),
    .outStreamSizeInBits_V_write(fixedHuffman86_U0_outStreamSizeInBits_V_write),
    .ap_ext_blocking_n(fixedHuffman86_U0_ap_ext_blocking_n),
    .ap_str_blocking_n(fixedHuffman86_U0_ap_str_blocking_n),
    .ap_int_blocking_n(fixedHuffman86_U0_ap_int_blocking_n)
);

gZip_cu_fixedHuffman87 fixedHuffman87_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(fixedHuffman87_U0_ap_start),
    .ap_done(fixedHuffman87_U0_ap_done),
    .ap_continue(fixedHuffman87_U0_ap_continue),
    .ap_idle(fixedHuffman87_U0_ap_idle),
    .ap_ready(fixedHuffman87_U0_ap_ready),
    .inStream_V_V_dout(inStream4_V_V_dout),
    .inStream_V_V_empty_n(inStream4_V_V_empty_n),
    .inStream_V_V_read(fixedHuffman87_U0_inStream_V_V_read),
    .outStream_V_V_din(fixedHuffman87_U0_outStream_V_V_din),
    .outStream_V_V_full_n(outStream4_V_V_full_n),
    .outStream_V_V_write(fixedHuffman87_U0_outStream_V_V_write),
    .outStreamSizeInBits_V_din(fixedHuffman87_U0_outStreamSizeInBits_V_din),
    .outStreamSizeInBits_V_full_n(outStreamSizeInBits4_V_full_n),
    .outStreamSizeInBits_V_write(fixedHuffman87_U0_outStreamSizeInBits_V_write),
    .ap_ext_blocking_n(fixedHuffman87_U0_ap_ext_blocking_n),
    .ap_str_blocking_n(fixedHuffman87_U0_ap_str_blocking_n),
    .ap_int_blocking_n(fixedHuffman87_U0_ap_int_blocking_n)
);

gZip_cu_fixedHuffman88 fixedHuffman88_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(fixedHuffman88_U0_ap_start),
    .ap_done(fixedHuffman88_U0_ap_done),
    .ap_continue(fixedHuffman88_U0_ap_continue),
    .ap_idle(fixedHuffman88_U0_ap_idle),
    .ap_ready(fixedHuffman88_U0_ap_ready),
    .inStream_V_V_dout(inStream5_V_V_dout),
    .inStream_V_V_empty_n(inStream5_V_V_empty_n),
    .inStream_V_V_read(fixedHuffman88_U0_inStream_V_V_read),
    .outStream_V_V_din(fixedHuffman88_U0_outStream_V_V_din),
    .outStream_V_V_full_n(outStream5_V_V_full_n),
    .outStream_V_V_write(fixedHuffman88_U0_outStream_V_V_write),
    .outStreamSizeInBits_V_din(fixedHuffman88_U0_outStreamSizeInBits_V_din),
    .outStreamSizeInBits_V_full_n(outStreamSizeInBits5_V_full_n),
    .outStreamSizeInBits_V_write(fixedHuffman88_U0_outStreamSizeInBits_V_write),
    .ap_ext_blocking_n(fixedHuffman88_U0_ap_ext_blocking_n),
    .ap_str_blocking_n(fixedHuffman88_U0_ap_str_blocking_n),
    .ap_int_blocking_n(fixedHuffman88_U0_ap_int_blocking_n)
);

gZip_cu_fixedHuffman89 fixedHuffman89_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(fixedHuffman89_U0_ap_start),
    .ap_done(fixedHuffman89_U0_ap_done),
    .ap_continue(fixedHuffman89_U0_ap_continue),
    .ap_idle(fixedHuffman89_U0_ap_idle),
    .ap_ready(fixedHuffman89_U0_ap_ready),
    .inStream_V_V_dout(inStream6_V_V_dout),
    .inStream_V_V_empty_n(inStream6_V_V_empty_n),
    .inStream_V_V_read(fixedHuffman89_U0_inStream_V_V_read),
    .outStream_V_V_din(fixedHuffman89_U0_outStream_V_V_din),
    .outStream_V_V_full_n(outStream6_V_V_full_n),
    .outStream_V_V_write(fixedHuffman89_U0_outStream_V_V_write),
    .outStreamSizeInBits_V_din(fixedHuffman89_U0_outStreamSizeInBits_V_din),
    .outStreamSizeInBits_V_full_n(outStreamSizeInBits6_V_full_n),
    .outStreamSizeInBits_V_write(fixedHuffman89_U0_outStreamSizeInBits_V_write),
    .ap_ext_blocking_n(fixedHuffman89_U0_ap_ext_blocking_n),
    .ap_str_blocking_n(fixedHuffman89_U0_ap_str_blocking_n),
    .ap_int_blocking_n(fixedHuffman89_U0_ap_int_blocking_n)
);

gZip_cu_fixedHuffman fixedHuffman_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(fixedHuffman_U0_ap_start),
    .ap_done(fixedHuffman_U0_ap_done),
    .ap_continue(fixedHuffman_U0_ap_continue),
    .ap_idle(fixedHuffman_U0_ap_idle),
    .ap_ready(fixedHuffman_U0_ap_ready),
    .inStream_V_V_dout(inStream7_V_V_dout),
    .inStream_V_V_empty_n(inStream7_V_V_empty_n),
    .inStream_V_V_read(fixedHuffman_U0_inStream_V_V_read),
    .outStream_V_V_din(fixedHuffman_U0_outStream_V_V_din),
    .outStream_V_V_full_n(outStream7_V_V_full_n),
    .outStream_V_V_write(fixedHuffman_U0_outStream_V_V_write),
    .outStreamSizeInBits_V_din(fixedHuffman_U0_outStreamSizeInBits_V_din),
    .outStreamSizeInBits_V_full_n(outStreamSizeInBits7_V_full_n),
    .outStreamSizeInBits_V_write(fixedHuffman_U0_outStreamSizeInBits_V_write),
    .ap_ext_blocking_n(fixedHuffman_U0_ap_ext_blocking_n),
    .ap_str_blocking_n(fixedHuffman_U0_ap_str_blocking_n),
    .ap_int_blocking_n(fixedHuffman_U0_ap_int_blocking_n)
);

gZip_cu_merger merger_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(merger_U0_ap_start),
    .ap_done(merger_U0_ap_done),
    .ap_continue(merger_U0_ap_continue),
    .ap_idle(merger_U0_ap_idle),
    .ap_ready(merger_U0_ap_ready),
    .outStream_V_V_din(merger_U0_outStream_V_V_din),
    .outStream_V_V_full_n(outStream_V_V_full_n),
    .outStream_V_V_write(merger_U0_outStream_V_V_write),
    .inStream0_V_V_dout(outStream0_V_V_dout),
    .inStream0_V_V_empty_n(outStream0_V_V_empty_n),
    .inStream0_V_V_read(merger_U0_inStream0_V_V_read),
    .inStreamSizeInBits0_V_dout(outStreamSizeInBits0_V_dout),
    .inStreamSizeInBits0_V_empty_n(outStreamSizeInBits0_V_empty_n),
    .inStreamSizeInBits0_V_read(merger_U0_inStreamSizeInBits0_V_read),
    .inStream1_V_V_dout(outStream1_V_V_dout),
    .inStream1_V_V_empty_n(outStream1_V_V_empty_n),
    .inStream1_V_V_read(merger_U0_inStream1_V_V_read),
    .inStreamSizeInBits1_V_dout(outStreamSizeInBits1_V_dout),
    .inStreamSizeInBits1_V_empty_n(outStreamSizeInBits1_V_empty_n),
    .inStreamSizeInBits1_V_read(merger_U0_inStreamSizeInBits1_V_read),
    .inStream2_V_V_dout(outStream2_V_V_dout),
    .inStream2_V_V_empty_n(outStream2_V_V_empty_n),
    .inStream2_V_V_read(merger_U0_inStream2_V_V_read),
    .inStreamSizeInBits2_V_dout(outStreamSizeInBits2_V_dout),
    .inStreamSizeInBits2_V_empty_n(outStreamSizeInBits2_V_empty_n),
    .inStreamSizeInBits2_V_read(merger_U0_inStreamSizeInBits2_V_read),
    .inStream3_V_V_dout(outStream3_V_V_dout),
    .inStream3_V_V_empty_n(outStream3_V_V_empty_n),
    .inStream3_V_V_read(merger_U0_inStream3_V_V_read),
    .inStreamSizeInBits3_V_dout(outStreamSizeInBits3_V_dout),
    .inStreamSizeInBits3_V_empty_n(outStreamSizeInBits3_V_empty_n),
    .inStreamSizeInBits3_V_read(merger_U0_inStreamSizeInBits3_V_read),
    .inStream4_V_V_dout(outStream4_V_V_dout),
    .inStream4_V_V_empty_n(outStream4_V_V_empty_n),
    .inStream4_V_V_read(merger_U0_inStream4_V_V_read),
    .inStreamSizeInBits4_V_dout(outStreamSizeInBits4_V_dout),
    .inStreamSizeInBits4_V_empty_n(outStreamSizeInBits4_V_empty_n),
    .inStreamSizeInBits4_V_read(merger_U0_inStreamSizeInBits4_V_read),
    .inStream5_V_V_dout(outStream5_V_V_dout),
    .inStream5_V_V_empty_n(outStream5_V_V_empty_n),
    .inStream5_V_V_read(merger_U0_inStream5_V_V_read),
    .inStreamSizeInBits5_V_dout(outStreamSizeInBits5_V_dout),
    .inStreamSizeInBits5_V_empty_n(outStreamSizeInBits5_V_empty_n),
    .inStreamSizeInBits5_V_read(merger_U0_inStreamSizeInBits5_V_read),
    .inStream6_V_V_dout(outStream6_V_V_dout),
    .inStream6_V_V_empty_n(outStream6_V_V_empty_n),
    .inStream6_V_V_read(merger_U0_inStream6_V_V_read),
    .inStreamSizeInBits6_V_dout(outStreamSizeInBits6_V_dout),
    .inStreamSizeInBits6_V_empty_n(outStreamSizeInBits6_V_empty_n),
    .inStreamSizeInBits6_V_read(merger_U0_inStreamSizeInBits6_V_read),
    .inStream7_V_V_dout(outStream7_V_V_dout),
    .inStream7_V_V_empty_n(outStream7_V_V_empty_n),
    .inStream7_V_V_read(merger_U0_inStream7_V_V_read),
    .inStreamSizeInBits7_V_dout(outStreamSizeInBits7_V_dout),
    .inStreamSizeInBits7_V_empty_n(outStreamSizeInBits7_V_empty_n),
    .inStreamSizeInBits7_V_read(merger_U0_inStreamSizeInBits7_V_read),
    .input_size_dout(input_size_c_i_dout),
    .input_size_empty_n(input_size_c_i_empty_n),
    .input_size_read(merger_U0_input_size_read),
    .ap_ext_blocking_n(merger_U0_ap_ext_blocking_n),
    .ap_str_blocking_n(merger_U0_ap_str_blocking_n),
    .ap_int_blocking_n(merger_U0_ap_int_blocking_n)
);

gZip_cu_fifo_w256_d256_A inStream0_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(splitter_U0_outStream0_V_V_din),
    .if_full_n(inStream0_V_V_full_n),
    .if_write(splitter_U0_outStream0_V_V_write),
    .if_dout(inStream0_V_V_dout),
    .if_empty_n(inStream0_V_V_empty_n),
    .if_read(fixedHuffman83_U0_inStream_V_V_read)
);

gZip_cu_fifo_w256_d256_A inStream1_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(splitter_U0_outStream1_V_V_din),
    .if_full_n(inStream1_V_V_full_n),
    .if_write(splitter_U0_outStream1_V_V_write),
    .if_dout(inStream1_V_V_dout),
    .if_empty_n(inStream1_V_V_empty_n),
    .if_read(fixedHuffman84_U0_inStream_V_V_read)
);

gZip_cu_fifo_w256_d256_A inStream2_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(splitter_U0_outStream2_V_V_din),
    .if_full_n(inStream2_V_V_full_n),
    .if_write(splitter_U0_outStream2_V_V_write),
    .if_dout(inStream2_V_V_dout),
    .if_empty_n(inStream2_V_V_empty_n),
    .if_read(fixedHuffman85_U0_inStream_V_V_read)
);

gZip_cu_fifo_w256_d256_A inStream3_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(splitter_U0_outStream3_V_V_din),
    .if_full_n(inStream3_V_V_full_n),
    .if_write(splitter_U0_outStream3_V_V_write),
    .if_dout(inStream3_V_V_dout),
    .if_empty_n(inStream3_V_V_empty_n),
    .if_read(fixedHuffman86_U0_inStream_V_V_read)
);

gZip_cu_fifo_w256_d256_A inStream4_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(splitter_U0_outStream4_V_V_din),
    .if_full_n(inStream4_V_V_full_n),
    .if_write(splitter_U0_outStream4_V_V_write),
    .if_dout(inStream4_V_V_dout),
    .if_empty_n(inStream4_V_V_empty_n),
    .if_read(fixedHuffman87_U0_inStream_V_V_read)
);

gZip_cu_fifo_w256_d256_A inStream5_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(splitter_U0_outStream5_V_V_din),
    .if_full_n(inStream5_V_V_full_n),
    .if_write(splitter_U0_outStream5_V_V_write),
    .if_dout(inStream5_V_V_dout),
    .if_empty_n(inStream5_V_V_empty_n),
    .if_read(fixedHuffman88_U0_inStream_V_V_read)
);

gZip_cu_fifo_w256_d256_A inStream6_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(splitter_U0_outStream6_V_V_din),
    .if_full_n(inStream6_V_V_full_n),
    .if_write(splitter_U0_outStream6_V_V_write),
    .if_dout(inStream6_V_V_dout),
    .if_empty_n(inStream6_V_V_empty_n),
    .if_read(fixedHuffman89_U0_inStream_V_V_read)
);

gZip_cu_fifo_w256_d256_A inStream7_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(splitter_U0_outStream7_V_V_din),
    .if_full_n(inStream7_V_V_full_n),
    .if_write(splitter_U0_outStream7_V_V_write),
    .if_dout(inStream7_V_V_dout),
    .if_empty_n(inStream7_V_V_empty_n),
    .if_read(fixedHuffman_U0_inStream_V_V_read)
);

gZip_cu_fifo_w64_d3_A input_size_c_i_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(splitter_U0_input_size_out_din),
    .if_full_n(input_size_c_i_full_n),
    .if_write(splitter_U0_input_size_out_write),
    .if_dout(input_size_c_i_dout),
    .if_empty_n(input_size_c_i_empty_n),
    .if_read(merger_U0_input_size_read)
);

gZip_cu_fifo_w64_d256_A outStream0_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fixedHuffman83_U0_outStream_V_V_din),
    .if_full_n(outStream0_V_V_full_n),
    .if_write(fixedHuffman83_U0_outStream_V_V_write),
    .if_dout(outStream0_V_V_dout),
    .if_empty_n(outStream0_V_V_empty_n),
    .if_read(merger_U0_inStream0_V_V_read)
);

gZip_cu_fifo_w16_d8_A outStreamSizeInBits0_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fixedHuffman83_U0_outStreamSizeInBits_V_din),
    .if_full_n(outStreamSizeInBits0_V_full_n),
    .if_write(fixedHuffman83_U0_outStreamSizeInBits_V_write),
    .if_dout(outStreamSizeInBits0_V_dout),
    .if_empty_n(outStreamSizeInBits0_V_empty_n),
    .if_read(merger_U0_inStreamSizeInBits0_V_read)
);

gZip_cu_fifo_w64_d256_A outStream1_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fixedHuffman84_U0_outStream_V_V_din),
    .if_full_n(outStream1_V_V_full_n),
    .if_write(fixedHuffman84_U0_outStream_V_V_write),
    .if_dout(outStream1_V_V_dout),
    .if_empty_n(outStream1_V_V_empty_n),
    .if_read(merger_U0_inStream1_V_V_read)
);

gZip_cu_fifo_w16_d8_A outStreamSizeInBits1_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fixedHuffman84_U0_outStreamSizeInBits_V_din),
    .if_full_n(outStreamSizeInBits1_V_full_n),
    .if_write(fixedHuffman84_U0_outStreamSizeInBits_V_write),
    .if_dout(outStreamSizeInBits1_V_dout),
    .if_empty_n(outStreamSizeInBits1_V_empty_n),
    .if_read(merger_U0_inStreamSizeInBits1_V_read)
);

gZip_cu_fifo_w64_d256_A outStream2_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fixedHuffman85_U0_outStream_V_V_din),
    .if_full_n(outStream2_V_V_full_n),
    .if_write(fixedHuffman85_U0_outStream_V_V_write),
    .if_dout(outStream2_V_V_dout),
    .if_empty_n(outStream2_V_V_empty_n),
    .if_read(merger_U0_inStream2_V_V_read)
);

gZip_cu_fifo_w16_d8_A outStreamSizeInBits2_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fixedHuffman85_U0_outStreamSizeInBits_V_din),
    .if_full_n(outStreamSizeInBits2_V_full_n),
    .if_write(fixedHuffman85_U0_outStreamSizeInBits_V_write),
    .if_dout(outStreamSizeInBits2_V_dout),
    .if_empty_n(outStreamSizeInBits2_V_empty_n),
    .if_read(merger_U0_inStreamSizeInBits2_V_read)
);

gZip_cu_fifo_w64_d256_A outStream3_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fixedHuffman86_U0_outStream_V_V_din),
    .if_full_n(outStream3_V_V_full_n),
    .if_write(fixedHuffman86_U0_outStream_V_V_write),
    .if_dout(outStream3_V_V_dout),
    .if_empty_n(outStream3_V_V_empty_n),
    .if_read(merger_U0_inStream3_V_V_read)
);

gZip_cu_fifo_w16_d8_A outStreamSizeInBits3_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fixedHuffman86_U0_outStreamSizeInBits_V_din),
    .if_full_n(outStreamSizeInBits3_V_full_n),
    .if_write(fixedHuffman86_U0_outStreamSizeInBits_V_write),
    .if_dout(outStreamSizeInBits3_V_dout),
    .if_empty_n(outStreamSizeInBits3_V_empty_n),
    .if_read(merger_U0_inStreamSizeInBits3_V_read)
);

gZip_cu_fifo_w64_d256_A outStream4_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fixedHuffman87_U0_outStream_V_V_din),
    .if_full_n(outStream4_V_V_full_n),
    .if_write(fixedHuffman87_U0_outStream_V_V_write),
    .if_dout(outStream4_V_V_dout),
    .if_empty_n(outStream4_V_V_empty_n),
    .if_read(merger_U0_inStream4_V_V_read)
);

gZip_cu_fifo_w16_d8_A outStreamSizeInBits4_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fixedHuffman87_U0_outStreamSizeInBits_V_din),
    .if_full_n(outStreamSizeInBits4_V_full_n),
    .if_write(fixedHuffman87_U0_outStreamSizeInBits_V_write),
    .if_dout(outStreamSizeInBits4_V_dout),
    .if_empty_n(outStreamSizeInBits4_V_empty_n),
    .if_read(merger_U0_inStreamSizeInBits4_V_read)
);

gZip_cu_fifo_w64_d256_A outStream5_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fixedHuffman88_U0_outStream_V_V_din),
    .if_full_n(outStream5_V_V_full_n),
    .if_write(fixedHuffman88_U0_outStream_V_V_write),
    .if_dout(outStream5_V_V_dout),
    .if_empty_n(outStream5_V_V_empty_n),
    .if_read(merger_U0_inStream5_V_V_read)
);

gZip_cu_fifo_w16_d8_A outStreamSizeInBits5_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fixedHuffman88_U0_outStreamSizeInBits_V_din),
    .if_full_n(outStreamSizeInBits5_V_full_n),
    .if_write(fixedHuffman88_U0_outStreamSizeInBits_V_write),
    .if_dout(outStreamSizeInBits5_V_dout),
    .if_empty_n(outStreamSizeInBits5_V_empty_n),
    .if_read(merger_U0_inStreamSizeInBits5_V_read)
);

gZip_cu_fifo_w64_d256_A outStream6_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fixedHuffman89_U0_outStream_V_V_din),
    .if_full_n(outStream6_V_V_full_n),
    .if_write(fixedHuffman89_U0_outStream_V_V_write),
    .if_dout(outStream6_V_V_dout),
    .if_empty_n(outStream6_V_V_empty_n),
    .if_read(merger_U0_inStream6_V_V_read)
);

gZip_cu_fifo_w16_d8_A outStreamSizeInBits6_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fixedHuffman89_U0_outStreamSizeInBits_V_din),
    .if_full_n(outStreamSizeInBits6_V_full_n),
    .if_write(fixedHuffman89_U0_outStreamSizeInBits_V_write),
    .if_dout(outStreamSizeInBits6_V_dout),
    .if_empty_n(outStreamSizeInBits6_V_empty_n),
    .if_read(merger_U0_inStreamSizeInBits6_V_read)
);

gZip_cu_fifo_w64_d256_A outStream7_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fixedHuffman_U0_outStream_V_V_din),
    .if_full_n(outStream7_V_V_full_n),
    .if_write(fixedHuffman_U0_outStream_V_V_write),
    .if_dout(outStream7_V_V_dout),
    .if_empty_n(outStream7_V_V_empty_n),
    .if_read(merger_U0_inStream7_V_V_read)
);

gZip_cu_fifo_w16_d8_A outStreamSizeInBits7_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fixedHuffman_U0_outStreamSizeInBits_V_din),
    .if_full_n(outStreamSizeInBits7_V_full_n),
    .if_write(fixedHuffman_U0_outStreamSizeInBits_V_write),
    .if_dout(outStreamSizeInBits7_V_dout),
    .if_empty_n(outStreamSizeInBits7_V_empty_n),
    .if_read(merger_U0_inStreamSizeInBits7_V_read)
);

gZip_cu_start_for_fixedHuffman83_U0 start_for_fixedHuffman83_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_fixedHuffman83_U0_din),
    .if_full_n(start_for_fixedHuffman83_U0_full_n),
    .if_write(splitter_U0_start_write),
    .if_dout(start_for_fixedHuffman83_U0_dout),
    .if_empty_n(start_for_fixedHuffman83_U0_empty_n),
    .if_read(fixedHuffman83_U0_ap_ready)
);

gZip_cu_start_for_fixedHuffman84_U0 start_for_fixedHuffman84_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_fixedHuffman84_U0_din),
    .if_full_n(start_for_fixedHuffman84_U0_full_n),
    .if_write(splitter_U0_start_write),
    .if_dout(start_for_fixedHuffman84_U0_dout),
    .if_empty_n(start_for_fixedHuffman84_U0_empty_n),
    .if_read(fixedHuffman84_U0_ap_ready)
);

gZip_cu_start_for_fixedHuffman85_U0 start_for_fixedHuffman85_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_fixedHuffman85_U0_din),
    .if_full_n(start_for_fixedHuffman85_U0_full_n),
    .if_write(splitter_U0_start_write),
    .if_dout(start_for_fixedHuffman85_U0_dout),
    .if_empty_n(start_for_fixedHuffman85_U0_empty_n),
    .if_read(fixedHuffman85_U0_ap_ready)
);

gZip_cu_start_for_fixedHuffman86_U0 start_for_fixedHuffman86_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_fixedHuffman86_U0_din),
    .if_full_n(start_for_fixedHuffman86_U0_full_n),
    .if_write(splitter_U0_start_write),
    .if_dout(start_for_fixedHuffman86_U0_dout),
    .if_empty_n(start_for_fixedHuffman86_U0_empty_n),
    .if_read(fixedHuffman86_U0_ap_ready)
);

gZip_cu_start_for_fixedHuffman87_U0 start_for_fixedHuffman87_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_fixedHuffman87_U0_din),
    .if_full_n(start_for_fixedHuffman87_U0_full_n),
    .if_write(splitter_U0_start_write),
    .if_dout(start_for_fixedHuffman87_U0_dout),
    .if_empty_n(start_for_fixedHuffman87_U0_empty_n),
    .if_read(fixedHuffman87_U0_ap_ready)
);

gZip_cu_start_for_fixedHuffman88_U0 start_for_fixedHuffman88_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_fixedHuffman88_U0_din),
    .if_full_n(start_for_fixedHuffman88_U0_full_n),
    .if_write(splitter_U0_start_write),
    .if_dout(start_for_fixedHuffman88_U0_dout),
    .if_empty_n(start_for_fixedHuffman88_U0_empty_n),
    .if_read(fixedHuffman88_U0_ap_ready)
);

gZip_cu_start_for_fixedHuffman89_U0 start_for_fixedHuffman89_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_fixedHuffman89_U0_din),
    .if_full_n(start_for_fixedHuffman89_U0_full_n),
    .if_write(splitter_U0_start_write),
    .if_dout(start_for_fixedHuffman89_U0_dout),
    .if_empty_n(start_for_fixedHuffman89_U0_empty_n),
    .if_read(fixedHuffman89_U0_ap_ready)
);

gZip_cu_start_for_fixedHuffman_U0 start_for_fixedHuffman_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_fixedHuffman_U0_din),
    .if_full_n(start_for_fixedHuffman_U0_full_n),
    .if_write(splitter_U0_start_write),
    .if_dout(start_for_fixedHuffman_U0_dout),
    .if_empty_n(start_for_fixedHuffman_U0_empty_n),
    .if_read(fixedHuffman_U0_ap_ready)
);

gZip_cu_start_for_merger_U0 start_for_merger_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_merger_U0_din),
    .if_full_n(start_for_merger_U0_full_n),
    .if_write(splitter_U0_start_write),
    .if_dout(start_for_merger_U0_dout),
    .if_empty_n(start_for_merger_U0_empty_n),
    .if_read(merger_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

assign ap_done = merger_U0_ap_done;

assign ap_ext_blocking_cur_n = 1'b1;

assign ap_ext_blocking_n = (ap_ext_blocking_sub_n & ap_ext_blocking_cur_n);

assign ap_ext_blocking_sub_n = (splitter_U0_ap_ext_blocking_n & merger_U0_ap_ext_blocking_n & fixedHuffman_U0_ap_ext_blocking_n & fixedHuffman89_U0_ap_ext_blocking_n & fixedHuffman88_U0_ap_ext_blocking_n & fixedHuffman87_U0_ap_ext_blocking_n & fixedHuffman86_U0_ap_ext_blocking_n & fixedHuffman85_U0_ap_ext_blocking_n & fixedHuffman84_U0_ap_ext_blocking_n & fixedHuffman83_U0_ap_ext_blocking_n);

assign ap_idle = (splitter_U0_ap_idle & merger_U0_ap_idle & fixedHuffman_U0_ap_idle & fixedHuffman89_U0_ap_idle & fixedHuffman88_U0_ap_idle & fixedHuffman87_U0_ap_idle & fixedHuffman86_U0_ap_idle & fixedHuffman85_U0_ap_idle & fixedHuffman84_U0_ap_idle & fixedHuffman83_U0_ap_idle);

assign ap_int_blocking_cur_n = 1'b1;

assign ap_int_blocking_n = (ap_int_blocking_sub_n & ap_int_blocking_cur_n);

assign ap_int_blocking_sub_n = (splitter_U0_ap_int_blocking_n & merger_U0_ap_int_blocking_n & fixedHuffman_U0_ap_int_blocking_n & fixedHuffman89_U0_ap_int_blocking_n & fixedHuffman88_U0_ap_int_blocking_n & fixedHuffman87_U0_ap_int_blocking_n & fixedHuffman86_U0_ap_int_blocking_n & fixedHuffman85_U0_ap_int_blocking_n & fixedHuffman84_U0_ap_int_blocking_n & fixedHuffman83_U0_ap_int_blocking_n);

assign ap_ready = internal_ap_ready;

assign ap_str_blocking_cur_n = 1'b1;

assign ap_str_blocking_n = (ap_str_blocking_sub_n & ap_str_blocking_cur_n);

assign ap_str_blocking_sub_n = (splitter_U0_ap_str_blocking_n & merger_U0_ap_str_blocking_n & fixedHuffman_U0_ap_str_blocking_n & fixedHuffman89_U0_ap_str_blocking_n & fixedHuffman88_U0_ap_str_blocking_n & fixedHuffman87_U0_ap_str_blocking_n & fixedHuffman86_U0_ap_str_blocking_n & fixedHuffman85_U0_ap_str_blocking_n & fixedHuffman84_U0_ap_str_blocking_n & fixedHuffman83_U0_ap_str_blocking_n);

assign ap_sync_continue = ap_continue;

assign ap_sync_done = merger_U0_ap_done;

assign ap_sync_ready = splitter_U0_ap_ready;

assign fixedHuffman83_U0_ap_continue = 1'b1;

assign fixedHuffman83_U0_ap_start = start_for_fixedHuffman83_U0_empty_n;

assign fixedHuffman83_U0_start_full_n = 1'b1;

assign fixedHuffman83_U0_start_write = 1'b0;

assign fixedHuffman84_U0_ap_continue = 1'b1;

assign fixedHuffman84_U0_ap_start = start_for_fixedHuffman84_U0_empty_n;

assign fixedHuffman84_U0_start_full_n = 1'b1;

assign fixedHuffman84_U0_start_write = 1'b0;

assign fixedHuffman85_U0_ap_continue = 1'b1;

assign fixedHuffman85_U0_ap_start = start_for_fixedHuffman85_U0_empty_n;

assign fixedHuffman85_U0_start_full_n = 1'b1;

assign fixedHuffman85_U0_start_write = 1'b0;

assign fixedHuffman86_U0_ap_continue = 1'b1;

assign fixedHuffman86_U0_ap_start = start_for_fixedHuffman86_U0_empty_n;

assign fixedHuffman86_U0_start_full_n = 1'b1;

assign fixedHuffman86_U0_start_write = 1'b0;

assign fixedHuffman87_U0_ap_continue = 1'b1;

assign fixedHuffman87_U0_ap_start = start_for_fixedHuffman87_U0_empty_n;

assign fixedHuffman87_U0_start_full_n = 1'b1;

assign fixedHuffman87_U0_start_write = 1'b0;

assign fixedHuffman88_U0_ap_continue = 1'b1;

assign fixedHuffman88_U0_ap_start = start_for_fixedHuffman88_U0_empty_n;

assign fixedHuffman88_U0_start_full_n = 1'b1;

assign fixedHuffman88_U0_start_write = 1'b0;

assign fixedHuffman89_U0_ap_continue = 1'b1;

assign fixedHuffman89_U0_ap_start = start_for_fixedHuffman89_U0_empty_n;

assign fixedHuffman89_U0_start_full_n = 1'b1;

assign fixedHuffman89_U0_start_write = 1'b0;

assign fixedHuffman_U0_ap_continue = 1'b1;

assign fixedHuffman_U0_ap_start = start_for_fixedHuffman_U0_empty_n;

assign fixedHuffman_U0_start_full_n = 1'b1;

assign fixedHuffman_U0_start_write = 1'b0;

assign inStream_V_V_read = splitter_U0_inStream_V_V_read;

assign input_size_read = splitter_U0_input_size_read;

assign internal_ap_ready = ap_sync_ready;

assign merger_U0_ap_continue = ap_continue;

assign merger_U0_ap_start = start_for_merger_U0_empty_n;

assign merger_U0_start_full_n = 1'b1;

assign merger_U0_start_write = 1'b0;

assign outStream_V_V_din = merger_U0_outStream_V_V_din;

assign outStream_V_V_write = merger_U0_outStream_V_V_write;

assign splitter_U0_ap_continue = 1'b1;

assign splitter_U0_ap_start = real_start;

assign splitter_U0_start_full_n = (start_for_merger_U0_full_n & start_for_fixedHuffman_U0_full_n & start_for_fixedHuffman89_U0_full_n & start_for_fixedHuffman88_U0_full_n & start_for_fixedHuffman87_U0_full_n & start_for_fixedHuffman86_U0_full_n & start_for_fixedHuffman85_U0_full_n & start_for_fixedHuffman84_U0_full_n & start_for_fixedHuffman83_U0_full_n);

assign start_for_fixedHuffman83_U0_din = 1'b1;

assign start_for_fixedHuffman84_U0_din = 1'b1;

assign start_for_fixedHuffman85_U0_din = 1'b1;

assign start_for_fixedHuffman86_U0_din = 1'b1;

assign start_for_fixedHuffman87_U0_din = 1'b1;

assign start_for_fixedHuffman88_U0_din = 1'b1;

assign start_for_fixedHuffman89_U0_din = 1'b1;

assign start_for_fixedHuffman_U0_din = 1'b1;

assign start_for_merger_U0_din = 1'b1;

assign start_out = real_start;

endmodule //gZip_cu_huffman_encode
